version: '3'

services:
    web:
        build: 
            context: .
            dockerfile: Dockerfile.dev
        ports:
            - "3000:3000"
        volumes:
            - /var/opt/react/node_modules
            - .:/var/opt/react
        stdin_open: true
    tests:
        build: 
            context: .
            dockerfile: Dockerfile.dev
        volumes:
            - /var/opt/react/node_modules
            - .:/var/opt/react
        stdin_open: true
        command: ["npm", "run", "test"]